version: '3.3'

services:

  tyler:
    build: ./
    depends_on:
      - redis
    environment:
      - HUBOT_ANSWER_TO_THE_ULTIMATE_QUESTION_OF_LIFE_THE_UNIVERSE_AND_EVERYTHING=42
      - REDIS_URL=redis://redis
    restart: unless-stopped

  redis:
    image: redis:5.0
    volumes:
      - redis-data:/data
    sysctls:
      net.core.somaxconn: '511'
    entrypoint: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis-data:
